# repos:
#   - repo: https://github.com/PyCQA/isort
#     rev: 5.10.1
#     hooks:
#       - id: isort
#         name: Sort Imports (isort)
#         verbose: true
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        name: Format Code (black)
        verbose: true
        exclude: ^dist/
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
       - id: trailing-whitespace
       - id: end-of-file-fixer
       - id: check-yaml
       - id: check-added-large-files
